project:
  type: book
  
book:
  title: "Manual-Applied-Spatial-Ecology"
  author: "W. David Walter"
  date: last-modified
  reader-mode: true

  page-footer:
    left: |
      Manual of Applied Spatial Ecology was written by W. David Walter.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: CoverSlide2.jpg
  favicon: CoverSlide2.jpg
  site-url: https://MASE.walterASEL/
  repo-url: https://github.com/walterASEL/Manual-of-Applied-Spatial-Ecology
  repo-branch: main
  repo-actions: [edit,issue]
  chapters:
    - index.Rmd
    - Preface.qmd
    - Intro.Rmd

    - part: Data-Manipulation-Management.qmd
      chapters:
        - MDprojections.Rmd
        - TimeLagScript.Rmd
        - SoilScript.Rmd
        - RasterScript.Rmd
        - GridScripts.Rmd
        - GridSystem2Script.Rmd
        - BufferScript.Rmd
        - MidAtlantic.Rmd
    
    - part: Climate-Data-Interpretion.qmd
      chapters:
        - ReadFilesScript.Rmd
        - Weather-Station-Code_Snowfall.Rmd
        - NetCDF_Script.Rmd

    - part: Movement-Methods.qmd
      chapters:
        - DMAdeerMovebank.Rmd
        - MovementScript.Rmd
        - DistanceUniqueBurst.Rmd
        - FPTscript.Rmd
        - RegTrajScript.Rmd
        - NSDscript.Rmd
        - TrajDynScript.Rmd

    - part: Home-Range-Estimation.qmd
      chapters:
        - HrefScript.Rmd
        - HlscvScript.Rmd
        - Panther_All4.Rmd
        - Panther_All4_amt.Rmd
        - BBMMscript.Rmd
        - MKDEcat_script.Rmd
        - CatdBBMM.Rmd

    - part: Landscape-Metrics.qmd
      chapters:
        - Frag_Auto.Rmd
        - PatchAnalystScript.Rmd

    - part: Resource-Selection.qmd
      chapters:
        - MCPscript.Rmd
        - LinearDistScript.Rmd
        - MD_DataPrep.Rmd
        - MuledeerSR.Rmd
        - LogisticRSF.Rmd
        - NegBinomial.Rmd
        
format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "W. David Walter"
    callout-appearance: simple
  
  #pdf: 
    #documentclass: scrbook
    
editor: visual