---
title: "Preface"
---

The purpose of this manual is to assist researchers on methods for data management and analysis using the R environment or other software after data has been collected in the field. The impetus behind this manual was from many years of frustration in trying to analyze data in R using code and forgetting how it was done upon completion of a study. We wanted to find a way to avoid needing to search computers for folders to find old R code then try to remember what we did to the data to get the code to run properly. Over the years, advancements in data handling and manipulation, GIS capabilities, and methods of estimators for home range, movements, resource selection, and spatial epidemiology have occurred within the R environment. Program R is free and used by researchers world-wide but R also provides a platform to create and display spatial layers without the need for the variety of GUI software, free or otherwise. Furthermore, analyzing spatial data in R enables statistical analysis of data without the errors that may arise from bringing data from spreadsheet or GIS software to statistical programs. We would like to stress that this manual is not the authority on all topics presented herein. Our goal was to create an online manual that could be easily followed by researchers, biologists, or graduate students to analyze their data in R. Although the user would benefit from general introductory knowledge of using R and ArcMap, most of the manual is for mid-level users of R that need guidance beyond the basics of introductory R and GIS coureses. We also provide numerous citations throughout each section should the user choose to learn the theory or more details behind each topic. In addition, this manual provides a handy outline of course materials for an Applied Spatial Ecology course that will surely expand or change as the field evolves. As time permits and errors are brought to our attention, we plan to update and correct problems so be sure to send any corrections or comments our way.

Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government.

**Recommended citation**:

Walter, W.D. Manual of Applied Spatial Ecology. Walter Applied Spatial Ecology Lab, Pennsylvania State University, University Park. Access Date. <http://ecosystems.psu.edu/research/labs/walter-lab>.

\newpage

**Acknowledgments**

Numerous colleagues have provide assistance with R packages they created or with code they have provided in some other form. We would be remiss if we failed to thank these colleagues for their hard work:

Sharon Baruch-Mordo, The Nature Conservancy, Fort Collins, CO 80524 ; [sbaruch-mordo\@tnc.org](mailto:sbaruch-mordo@tnc.org){.email} Simon Benhamou, Centre d'Ecologie Fonctionnelle et Evolutive, France Clément Calenge, Data Analysis Support Unit, Directorate for Studies and Research, National Office of Hunting and Wild Fauna, Saint Benoist - 78610 Auffargis, France Mevin Hooten, Colorado Cooperative Fish and Wildlife Research Unit, 201 Wagar Bldg, Colorado State University, Fort Collins, CO 8052 ; [Mevin.Hooten\@colostate.edu](mailto:Mevin.Hooten@colostate.edu){.email} Bill Kanapaux, Pennsylvania Cooperative Fish and Wildlife Research Unit, 406 Forest Resources Bldg., Pennyslvania State University, University Park, PA 16802 ; [wjk15\@psu.edu](mailto:wjk15@psu.edu){.email} Bart Kranstauber, Max Planck Institute for Ornithology, Eberhard-Gwinner-Str., 82319 Seewiesen; [bart.kranstauber\@uni-konstanz.de](mailto:bart.kranstauber@uni-konstanz.de){.email} Ryan Nielsen, West Inc.,415 W. 17th St. Suite 200, Cheyenne, WY 82001 ; [rnielson\@westinc](mailto:rnielson@westinc){.email}. com Glen Sargeant, Northern Prairie Wildlife Research Center, Jamestown, North Dakota; [glen_sargeant\@usgs.gov](mailto:glen_sargeant@usgs.gov){.email} Peter Singleton, USDA Forest Service, Pacific Northwest Research Station in Wenatchee, WA; [singlep\@u.washington.edu](mailto:singlep@u.washington.edu){.email} Marcó Smolla, Max Planck Institute for Ornithology, Dept. Migration and Immuno-ecology, Am Obstberg 1, 78315 Radolfzell, Germany; [msmolla\@orn.mpg.de](mailto:msmolla@orn.mpg.de){.email} Tyler Wagner, US Geological Survey, Pennsylvania Cooperative Fish and Wildlife Research Unit, 402 Forest Resources Bldg., Pennsylvania State University, University Park, PA 16802 ; [twagner\@psu.edu](mailto:twagner@psu.edu){.email}
